"""AI-learned ML features — auto-generated by the assistant.

These features are extracted from files and findings to improve
the ML model's ability to detect malware.
"""
import os
import math
import hashlib

def ext_toc_risk(finding):
    """Auto-generated: risk feature for .toc files."""
    path = str(finding.get("path", ""))
    return 1 if path.lower().endswith(".toc") else 0


def ext_cmd_risk(finding):
    """Auto-generated: risk feature for .cmd files."""
    path = str(finding.get("path", ""))
    return 1 if path.lower().endswith(".cmd") else 0


def ext_ps1_risk(finding):
    """Auto-generated: risk feature for .ps1 files."""
    path = str(finding.get("path", ""))
    return 1 if path.lower().endswith(".ps1") else 0
