"""Base knowledge seed for the assistant — loaded on first startup.

This gives the assistant foundational security knowledge so it can answer
questions intelligently without needing to be trained from scratch.
"""
BASE_KNOWLEDGE = [
    # --- Malware types ---
    ("ransomware", "Ransomware is a type of malware that encrypts files on a victim's system and demands payment (usually cryptocurrency) in exchange for the decryption key. It often spreads through phishing emails, malicious attachments, or exploit kits. Common families include WannaCry, Locky, Ryuk, Conti, and REvil. Indicators include mass file extension changes, ransom notes in directories, and shadow copy deletion."),
    ("trojan", "A trojan is malware disguised as legitimate software. Unlike viruses, trojans don't self-replicate — they rely on social engineering to trick users into running them. Common types include backdoor trojans (remote access), banking trojans (steal financial data), and downloader trojans (install more malware). Indicators include unexpected network connections to unknown IPs, suspicious processes running from temp directories, and registry persistence entries."),
    ("rootkit", "A rootkit is malware designed to hide its presence (or other malware) on a system by operating at the kernel or firmware level. Rootkits can intercept system calls, hide files and processes, and maintain persistent access. Detecting rootkits often requires memory analysis, boot-time scanning, or comparing system calls against known-good baselines. Indicators include hidden processes, modified system binaries, and unauthorized kernel modules."),
    ("keylogger", "A keylogger records keystrokes to capture passwords, credit card numbers, and other sensitive data. It can be software-based (hooking keyboard APIs) or hardware-based (USB devices). Indicators include unexpected keyboard hook DLLs, suspicious log files, and data being sent to unknown endpoints."),
    ("spyware", "Spyware secretly monitors user activity and collects data like browsing habits, credentials, and personal information. It often bundles with free software or installs through drive-by downloads. Indicators include unexpected browser redirects, new toolbars, slow system performance, and outbound traffic to tracking servers."),
    ("cryptominer", "A cryptominer (or cryptojacking malware) hijacks system resources to mine cryptocurrency without the user's consent. It causes high CPU/GPU usage, increased power consumption, and system slowdowns. Indicators include sustained high CPU usage from unknown processes, connections to mining pools, and suspicious scheduled tasks."),
    ("adware", "Adware displays unwanted advertisements, often through pop-ups or browser redirects. While not always dangerous, it can degrade system performance and may bundle with spyware. Indicators include unwanted toolbars, frequent pop-ups, browser homepage changes, and redirected searches."),
    ("backdoor", "A backdoor provides remote access to a system, bypassing normal authentication. It's often installed by other malware or planted by attackers during a breach. Indicators include unexpected listening ports, suspicious scheduled tasks, and unauthorized admin accounts."),
    ("c2_beacon", "A C2 (command and control) beacon is malware that periodically contacts an attacker-controlled server to receive commands or exfiltrate data. Common in APT attacks and ransomware campaigns. Indicators include regular beaconing traffic (fixed intervals), DNS queries to suspicious domains, and connections to known bad IPs."),
    ("worm", "A worm is self-replicating malware that spreads across networks without user interaction. Unlike viruses, worms don't need to attach to a host file. They exploit network vulnerabilities to propagate. Indicators include rapid network scanning, unexpected SMB/RPC traffic, and system instability across multiple machines."),

    # --- Security concepts ---
    ("yara", "YARA is a pattern matching tool used by malware researchers to identify and classify malware samples. YARA rules consist of string patterns (text, hex, or regex) and conditions. Rules can match on file content, file size, file type, and metadata. Writing good YARA rules requires balancing specificity (avoid false positives) with coverage (catch variants)."),
    ("ioc", "IOCs (Indicators of Compromise) are forensic artifacts that indicate a system may have been compromised. Common IOCs include file hashes (MD5, SHA256), IP addresses, domain names, URLs, registry keys, mutex names, and scheduled tasks. IOCs are shared through threat intelligence feeds and STIX/TAXII frameworks."),
    ("false_positive", "A false positive occurs when legitimate software or files are incorrectly flagged as malicious. Common causes include overly broad YARA rules, legitimate tools that use techniques similar to malware (like PowerShell scripts or packers), and files with suspicious-looking but benign patterns. Reducing false positives requires refining rules, adding exclusions, and using reputation-based checks."),
    ("quarantine", "Quarantine isolates detected threats by moving them to a secure location where they can't execute. Quarantined files are typically encrypted or stored in a restricted directory. This allows for analysis and potential restoration if the detection was a false positive. Files should remain in quarantine until verified as safe or confirmed as threats."),
    ("persistence", "Persistence mechanisms allow malware to survive system reboots. Common methods include registry Run keys, scheduled tasks, services, startup folders, WMI event subscriptions, and DLL hijacking. Detecting persistence requires monitoring these locations for unauthorized changes."),
    ("privilege_escalation", "Privilege escalation is when an attacker gains higher-level permissions than they should have. Vertical escalation goes from user to admin/root. Horizontal escalation moves between user accounts. Common techniques include exploiting unpatched vulnerabilities, token impersonation, and DLL injection into privileged processes."),
    ("lateral_movement", "Lateral movement is when an attacker spreads from one compromised system to others on the network. Techniques include pass-the-hash, RDP, SMB exploitation, and using stolen credentials. Detecting lateral movement requires monitoring network connections, authentication logs, and unusual admin tool usage."),
    ("exfiltration", "Data exfiltration is the unauthorized transfer of data from a system. Methods include HTTP/HTTPS uploads, DNS tunneling, FTP, cloud sync, and physical media. Detecting exfiltration requires monitoring outbound traffic volume, unusual protocols, and connections to unknown endpoints."),

    # --- Best practices ---
    ("incident_response", "Incident response follows a standard lifecycle: 1) Preparation — have tools and procedures ready. 2) Identification — detect and confirm the incident. 3) Containment — isolate affected systems to prevent spread. 4) Eradication — remove the threat. 5) Recovery — restore systems from clean backups. 6) Lessons learned — improve defenses. Always preserve evidence before cleaning."),
    ("remediation", "Remediation steps for malware: 1) Isolate the affected system from the network. 2) Identify the threat type and scope. 3) Quarantine malicious files. 4) Kill malicious processes. 5) Remove persistence mechanisms. 6) Patch the vulnerability that allowed entry. 7) Restore from clean backups if needed. 8) Monitor for reinfection. 9) Document everything for future reference."),
    ("threat_hunting", "Threat hunting is the proactive search for threats that have evaded automated detection. It involves analyzing network traffic, endpoint data, and logs for indicators of compromise. Good threat hunting uses hypotheses (e.g., 'if an attacker used living-off-the-land tools, look for unusual PowerShell execution patterns') and combines automated tools with analyst intuition."),

    # --- File types and risk ---
    ("executable_risk", "Executable files (.exe, .dll, .scr, .com, .pif, .bat, .cmd, .ps1, .vbs, .js) carry the highest malware risk because they can execute arbitrary code. Documents with macros (.docm, .xlsm) are also high risk. Archive files (.zip, .rar, .7z) are medium risk because they can contain malicious payloads. Always scan executables from untrusted sources before running them."),
    ("suspicious_paths", "Malware commonly installs to or runs from: temp directories (C:\\Windows\\Temp, C:\\Users\\*\\AppData\\Local\\Temp), AppData folders, ProgramData, the Downloads folder, and unusual system32 subdirectories. Files in these locations that don't belong to known software should be investigated."),
    ("suspicious_extensions", "Double extensions (e.g., report.pdf.exe) are a classic malware trick. Other suspicious patterns include .exe.scr, .doc.exe, and files with Unicode characters in names. Also watch for .lnk files in unusual locations and .hta (HTML Application) files."),
]
