/*
    Auto-generated by Assistant Trainer
    Threat: test_worm
    Severity: high
    Generated: 2026-08-20T05:33:28
*/

rule learned_test_worm : high
{
    strings:
    $str0 = "spread_network" nocase
    $str1 = "smb_exploit" nocase
    $str2 = "copy_self" nocase

    condition:
        any of them
}
