/*
    Auto-generated by Assistant Trainer
    Threat: custom_ransomware
    Severity: high
    Generated: 2026-08-20T05:00:08
*/

rule learned_custom_ransomware : high
{
    strings:
    $str0 = "encrypt_files" nocase
    $str1 = "bitcoin_wallet" nocase
    $str2 = ".locked_extension" nocase
    $str3 = "vss_delete_shadow" nocase

    condition:
        any of them
}
