/*
    Auto-generated by Assistant Trainer
    Threat: auto_ransomware
    Severity: critical
    Generated: 2026-08-20T05:19:34
*/

rule learned_auto_ransomware : critical
{
    strings:
    $str0 = "ransomware" nocase

    condition:
        any of them
}
