/*
    Auto-generated by Assistant Trainer
    Threat: auto_trojan
    Severity: high
    Generated: 2026-08-20T05:19:34
*/

rule learned_auto_trojan : high
{
    strings:
    $str0 = "trojan" nocase

    condition:
        any of them
}
